# -*- coding: utf-8 -*-
"""Corrective_RAG.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bb97djYQS4vQ54lhCq9KOyMf6sGnDLnN
"""

!pip install langchain langchain_core langchain_groq langchain_community langchain langgraph

from langchain_groq import ChatGroq
from google.colab import userdata

llm=ChatGroq(
    temperature=0,
    groq_api_key=userdata.get('Groq'),
    model_name="qwen/qwen3-32b",
    verbose=True
)

llm.invoke('hi')

! pip install langchain langchain-community langchain-huggingface chromadb beautifulsoup4 tiktoken sentence-transformers

# Install a compatible version of transformers
!pip install transformers==4.29.2

# from langchain_community.text_splitters import RecursiveCharacterTextSplitter

from langchain_text_splitters import RecursiveCharacterTextSplitter
from langchain_community.document_loaders import WebBaseLoader
from langchain_community.vectorstores import Chroma
from langchain_huggingface import HuggingFaceEmbeddings

EMBEDDING_MODEL = "sentence-transformers/all-MiniLM-L6-v2" # Defining EMBEDDING_MODEL

embeddings = HuggingFaceEmbeddings(
    model_name=EMBEDDING_MODEL
)

urls = [
    "https://lilianweng.github.io/posts/2023-06-23-agent/",
    "https://lilianweng.github.io/posts/2023-03-15-prompt-engineering/",
    "https://lilianweng.github.io/posts/2023-10-25-adv-attack-llm/",
]

docs = [WebBaseLoader(url).load() for url in urls]
docs_list = [item for sublist in docs for item in sublist]

text_splitter = RecursiveCharacterTextSplitter.from_tiktoken_encoder(
    chunk_size=250, chunk_overlap=50
)
doc_splits = text_splitter.split_documents(docs_list)

# Add to vectorDB
vectorstore = Chroma.from_documents(
    documents=doc_splits,
    collection_name="rag-chroma",
    embedding=embeddings,
)
retriever = vectorstore.as_retriever()

question = "tell me about the agent memory."

# Use the retriever to get relevant documents for the question
retrieved_docs = retriever.invoke(question)

# Take the page_content from the first retrieved document
doc_txt = retrieved_docs[0].page_content

print(retrieval_grader.invoke({"question": question, "document": doc_txt}))

! pip install langchain-classic

# New import path
from langchain_classic import hub

# Pull a prompt
prompt = hub.pull("hwchase17/react")

# from langchain import hub
from langchain_core.output_parsers import StrOutputParser

# Prompt
prompt = hub.pull("rlm/rag-prompt")

print(f"---PROMPT--- {prompt}")

# Post-processing
def format_docs(docs):
    return "\n\n".join(doc.page_content for doc in docs)


# Chain
rag_chain = prompt | llm | StrOutputParser()

# Run
question = "tell me about agent memory."
# Retrieve relevant documents, format them, and then invoke the RAG chain
generation = rag_chain.invoke({"context": format_docs(retriever.invoke(question)), "question": question})
print(generation)

from langgraph.graph import END, StateGraph, START

from typing import List

from typing_extensions import TypedDict

class State(TypedDict):
    """
    Represents the state of our graph.

    Attributes:
        question: question
        generation: LLM generation
        web_search: whether to add search
        documents: list of documents
    """

    question: str
    generation: str
    web_search: str
    documents: List[str]

workflow= StateGraph(State)

"""# Types of Node :-

- retrieve
- grade_documents
- generate
- transform query
- web search
"""

def retrieve(state):
  ''' Retrieve documents from the vector store  '''

  question=state['question']

  documents= docs = retriever.invoke(question)

  return {"documents": documents, "question": question}

from langchain_core.prompts import ChatPromptTemplate
from pydantic import BaseModel, Field


class GradeDocuments(BaseModel):
    """Binary score for relevance check on retrieved documents."""

    binary_score: str = Field(
        description="Documents are relevant to the question, 'yes' or 'no'"
    )

# LLM with function call
structured_llm_grader = llm.with_structured_output(GradeDocuments)
# Prompt
system = """You are a grader assessing relevance of a retrieved document to a user question. \n
    If the document contains keyword(s) or semantic meaning related to the question, grade it as relevant. \n
    Give a binary score 'yes' or 'no' score to indicate whether the document is relevant to the question."""
grade_prompt = ChatPromptTemplate.from_messages(
    [
        ("system", system),
        ("human", "Retrieved document: \n\n {document} \n\n User question: {question}"),
    ]
)

retrieval_grader = grade_prompt | structured_llm_grader

def grade_documents(state):
  '''
  determine wheather the document is relevent or not with the query asked by the user
    '''

  question=state['question']
  documents=state['documents']

  # Score each doc
  filtered_docs = []

  web_search = "No"



  for d in documents:
      score = retrieval_grader.invoke(
            {"question": question, "document": d.page_content}
        )
      grade = score.binary_score
      if grade == "yes":
            print("---GRADE: DOCUMENT RELEVANT---")
            filtered_docs.append(d)
      else:
            print("---GRADE: DOCUMENT NOT RELEVANT---")
            web_search = "Yes"
            continue
  return {"documents": filtered_docs, "question": question, "web_search": web_search}

def generate(state):
    """
    Generate answer

    Args:
        state (dict): The current graph state

    Returns:
        state (dict): New key added to state, generation, that contains LLM generation
    """

    print("---GENERATE---")

    question = state["question"]
    documents = state["documents"]

    generation = rag_chain.invoke({"context": documents, "question": question})

    return {"documents": documents, "question": question, "generation": generation}

def transform_query(state):
    """
    Transform the query to produce a better question.

    Args:
        state (dict): The current graph state

    Returns:
        state (dict): Updates question key with a re-phrased question
    """
    print("---TRANSFORM QUERY---")

    question = state["question"]

    documents = state["documents"]

    # Re-write question
    better_question = question_rewriter.invoke({"question": question})

    return {"documents": documents, "question": better_question}

### Search

from langchain_community.tools.tavily_search import TavilySearchResults
from google.colab import userdata

web_search_tool = TavilySearchResults(k=3, tavily_api_key=userdata.get('TAVILY_API_KEY'))

from langchain_core.documents import Document
def web_search(state):
    """
    Web search based on the re-phrased question.

    Args:
        state (dict): The current graph state

    Returns:
        state (dict): Updates documents key with appended web results
    """
    print("---WEB SEARCH---")

    question = state["question"]

    documents = state["documents"]

    # Web search
    docs = web_search_tool.invoke({"query": question})

    web_results = "\n".join([d["content"] for d in docs])

    web_results = Document(page_content=web_results)

    documents.append(web_results)

    return {"documents": documents, "question": question}

def decide_to_generate(state):

    if web_search == "Yes":
        return "transform_query"
    else:
        return "generate"

from langgraph.graph import END, StateGraph, START

workflow.add_node("retrieve", retrieve)  # retrieve
workflow.add_node("grade_documents", grade_documents)  # grade documents
workflow.add_node("generate", generate)  # generatae
workflow.add_node("transform_query", transform_query)  # transform_query
workflow.add_node("web_search_node", web_search)  # web search

# Build graph
workflow.add_edge(START, "retrieve")

workflow.add_edge("retrieve", "grade_documents")

workflow.add_conditional_edges("grade_documents", decide_to_generate, {"transform_query": "transform_query","generate": "generate",}),

workflow.add_edge("transform_query", "web_search_node")

workflow.add_edge("web_search_node", "generate")

workflow.add_edge("generate", END)

# Compile
app = workflow.compile()

app

from pprint import pprint

# Run
inputs = {"question": "tell me about the agent memory."}

for output in app.stream(inputs):
    for key, value in output.items():
        # Node
        pprint(f"Node '{key}':")
        # Optional: print full state at each node
        # pprint.pprint(value["keys"], indent=2, width=80, depth=None)
    pprint("\n---\n")
# Final generation
pprint(value["generation"])

# Run
inputs = {"question": "tell me about the taj mahal."}

for output in app.stream(inputs):
    for key, value in output.items():
        # Node
        pprint(f"Node '{key}':")
        # Optional: print full state at each node
        # pprint.pprint(value["keys"], indent=2, width=80, depth=None)
    pprint("\n---\n")
# Final generation
pprint(value["generation"])